### ISSUE TITLE
add dagger of a gate to the circuit

### ISSUE THREAD

**Issue by danielmpla** [cda-tum/mqt-qudits#30]
Hi,

how would I add the dagger of a gate to the circuit?

For me it is not clear from the Tutorial. I assumed it would be e.g. `circuit.csum([reg[i], reg[t]]).dag()`, however in `circ.instructions[0].__array__()` the non-dagger version is added.

Regards,
Daniel

**Comment by KevinMTO** [comment]
Hi Daniel, thanks for looking into it. The correct method is to use to_matrix(identity=[0,1,2]), 
a specific flag choice will give you a specific unitary.

- 0 : is the unitary (dagger or not) of the interaction on one or two lines.
- 1: is the unitary of 0 with identities on the lines between the target and control in case of entangling operation.
- 2: is the unitary of the operation on the whole circuit.

__array__() is a magic function to generate the unitary, shouldn't be used.  let me know if this helps :)
