### ISSUE TITLE
🐛 CSUM list index out of range for tnsim

### ISSUE THREAD

**Issue by danielmpla** [cda-tum/mqt-qudits#55]
### Environment information

- mqt.qudits: 0.1.0
- Python 3.12

### Description

When I create a quantum circuit with a register of 4 qudits each with dimension 5 add a CSUM.dagger on qudit 1 and 3 and execute it using `tnsim` I receive a `list index out of range` error.

Here is the execution stack:
- apply_identites_and_controls, matrix_factory.py:67
- generate_matrix, matrix_factory.py:35
- to_matrix, gate.py:95
- __contract_circuit, tnsim.py:78
- execute, tnsim.py:43
- run, tnsim.py:35
- create_circuit, 5_qudit_test.py:17
- <module>, 5_qudit_test.py:26

the issue seems to be, that in `apply_identites_and_controls, matrix_factory.py:67` we have `operator.itemgetter(*qudits_applied)([5,5,5])` instead of `operator.itemgetter(*qudits_applied)([5,5,5,5])`

### Expected behavior

Execute the CSUM.dagger Gate on qudits 1 and 3.

### How to Reproduce

```
from mqt.qudits.quantum_circuit import QuantumCircuit, QuantumRegister
from mqt.qudits.simulation import MQTQuditProvider
from mqt.qudits.visualisation import plot_state

def create_circuit():
    n = 4

    circuit = QuantumCircuit()
    reg = QuantumRegister("reg", n, dims=[5 for _ in range(n)])

    circuit.append(reg)

    circuit.csum([reg[1], reg[3]]).dag()

    provider = MQTQuditProvider()
    backend = provider.get_backend('tnsim')
    job = backend.run(circuit)
    result = job.result()

    state_vector = result.get_state_vector()
    print(state_vector)
    plot_state(state_vector, circuit)


if __name__ == '__main__':
    create_circuit()

```

**Comment by KevinMTO** [comment]
Solved, thanks a lot!
