### ISSUE TITLE
🐛 <Unable to build repository>

### ISSUE THREAD

**Issue by lukas-gerster** [cda-tum/mqt-qudits#70]
### Environment information

- OS: Ubuntu 24.04.1 LTS
- C++: CMake 3.28.3
- Python: v3.12.4
- mqt.core: main

### Description

I am trying to build the mqt package as a development package for testing, and CMake fails to find a suitable python version.
Attached is the error log
[errorlog.txt](https://github.com/user-attachments/files/17409175/errorlog.txt)

### How to Reproduce

Get the package via git.
Attempt to install via pip `pip install -ve .`

**Comment by burgholzer** [comment]
Hey 👋🏻 
Thanks for raising this issue!
Typically, these errors indicate that the Python installation on your system is not complete. Do you have `python3.12-dev` installed? (`sudo apt-get install python3.12-dev`)

Truly annoying how hard it is to properly set up Python even these days...

**Comment by lukas-gerster** [comment]
python3-dev is installed, but there seems to be some kind of issue:
```
❯ sudo apt install python3-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpython3.12-dev : Depends: libpython3.12-stdlib (= 3.12.3-1ubuntu0.2) but 3.12.4-1+jammy1 is to be installed
                     Depends: libpython3.12t64 (= 3.12.3-1ubuntu0.2) but it is not going to be installed
 python3.12-dev : Depends: python3.12 (= 3.12.3-1ubuntu0.2) but 3.12.4-1+jammy1 is to be installed
                  Depends: libpython3.12t64 (= 3.12.3-1ubuntu0.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by burgholzer** [comment]
Yeah. Unfortunately, your Python installation seems broken. 
It's definitely not the first time that I have seen this...
IIRC, I personally fixed this at some point by doing a complete reinstall of all Python-related system packages.

We do run CI on default Ubuntu images in GitHub actions and everything seems to "just work" there as well as locally on multiple development setups.

You could give `uv` (https://docs.astral.sh/uv/) a try:
```
curl -LsSf https://astral.sh/uv/install.sh | sh
uv venv --python 3.12
uv pip install -e.
```
You can tell `uv` to explicitly set up Python for you and not use the system Python via
```
uv venv --python 3.12 --python-preference only-managed
```

**Comment by lukas-gerster** [comment]
aptitude managed to resolve some version conflicts between different parts of python which mutually blocked each other from updating.
